export const authConstants = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGIN_SUCESS: "LOGIN_SUCESS",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCESS: "LOGOUT_SUCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",
};

export const userConstants = {
  USER_REGISTER_REQUEST: "USER_REGISTER_REQUEST",
  USER_REGISTER_SUCESS: "USER_REGISTER_SUCESS",
  USER_REGISTER_FAILURE: "USER_REGISTER_FAILURE",
};

export const donorConstants = {
  POST_DONOR_PROFILE_REQUEST: "POST_DONOR_PROFILE_REQUEST",
  POST_DONOR_PROFILE_SUCCESS: "POST_DONOR_PROFILE_SUCCESS",
  POST_DONOR_PROFILE_FAILURE: "POST_DONOR_PROFILE_FAILURE",
  GET_ALL_DONOR_PROFILE_REQUEST: "GET_ALL_DONOR_PROFILE_REQUEST",
  GET_ALL_DONOR_PROFILE_SUCCESS: "GET_ALL_DONOR_PROFILE_SUCCESS",
  GET_ALL_DONOR_PROFILE_FAILURE: "GET_ALL_DONOR_PROFILE_FAILURE",
  GET_DONOR_PROFILE_BY_BLOOD_GRP_REQUEST:
    "GET_DONOR_PROFILE_BY_BLOOD_GRP_REQUEST",
  GET_DONOR_PROFILE_BY_BLOOD_GRP_SUCCESS:
    "GET_DONOR_PROFILE_BY_BLOOD_GRP_SUCCESS",
  GET_DONOR_PROFILE_BY_BLOOD_GRP_FAILURE:
    "GET_DONOR_PROFILE_BY_BLOOD_GRP_FAILURE",
};

export const patientConstants = {
  POST_PATIENT_PROFILE_REQUEST: "POST_PATIENT_PROFILE_REQUEST",
  POST_PATIENT_PROFILE_SUCCESS: "POST_PATIENT_PROFILE_SUCCESS",
  POST_PATIENT_PROFILE_FAILURE: "POST_PATIENT_PROFILE_FAILURE",
  GET_ALL_PATIENT_PROFILE_REQUEST: "GET_ALL_PATIENT_PROFILE_REQUEST",
  GET_ALL_PATIENT_PROFILE_SUCCESS: "GET_ALL_PATIENT_PROFILE_SUCCESS",
  GET_ALL_PATIENT_PROFILE_FAILURE: "GET_ALL_PATIENT_PROFILE_FAILURE",
  GET_PATIENT_PROFILE_BY_BLOOD_GRP_REQUEST:
    "GET_PATIENT_PROFILE_BY_BLOOD_GRP_REQUEST",
  GET_PATIENT_PROFILE_BY_BLOOD_GRP_SUCCESS:
    "GET_PATIENT_PROFILE_BY_BLOOD_GRP_SUCCESS",
  GET_PATIENT_PROFILE_BY_BLOOD_GRP_FAILURE:
    "GET_PATIENT_PROFILE_BY_BLOOD_GRP_FAILURE",
};

export const categoryConstants = {
  GET_BLOOD_REQUEST: " GET_BLOOD_REQUEST",
  GET_BLOOD_SUCESS: " GET_BLOOD_SUCESS",
  GET_BLOOD_FAILURE: " GET_BLOOD_FAILURE",
};

export const covidConstants = {
  GET_OVERALL_STATS_REQUEST: " GET_OVERALL_STATS_REQUEST",
  GET_OVERALL_STATS_SUCESS: " GET_OVERALL_STATS_SUCESS",
  GET_OVERALL_STATS_FAILURE: " GET_OVERALL_STATS_FAILURE",
};


export const oxygenConstants = {
  POST_OXYGEN_REQUEST: "POST_OXYGEN_REQUEST",
  POST_OXYGEN_SUCCESS: "POST_OXYGEN_SUCCESS",
  POST_OXYGEN_FAILURE: "POST_OXYGEN_FAILURE",
  GET_ALL_OXYGEN_REQUEST: "GET_ALL_OXYGEN_REQUEST",
  GET_ALL_OXYGEN_SUCCESS: "GET_ALL_OXYGEN_SUCCESS",
  GET_ALL_OXYGEN_FAILURE: "GET_ALL_OXYGEN_FAILURE",
};